IF
Global("BFSSolSpawn","AR5500",0)
!InParty("dorn")
ReputationGT(Player1,13)
OR(6)
        Alignment(Player1,LAWFUL_GOOD)
        Alignment(Player1,NEUTRAL_GOOD)
        Alignment(Player1,CHAOTIC_GOOD)
        Alignment(Player1,LAWFUL_NEUTRAL)
		Alignment(Player1,NEUTRAL)
		Alignment(Player1,CHAOTIC_NEUTRAL)
THEN
    RESPONSE #100
PlaySound("CAS_M08")
CreateCreatureObject("BFSSOL",Player1,0,0,0)
SetGlobal("BFSSolSpawn","AR5500",1)
Continue()
END
